### ISSUE TITLE
"Event Date" should be "Incident Date"

### ISSUE THREAD

**Issue by dmontecino** [dmontecino/WH_Database#35]

**Comment by dmontecino** [comment]
Remove the time from the event date format
<img width="172" alt="Screen Shot 2023-12-07 at 1 59 55 PM" src="https://github.com/dmontecino/WH_Database/assets/9424808/1981690a-aca4-406c-be2f-a1b40f216756">

**Comment by wcs-sgallo** [comment]
This has been updated.
